name: Deploy to Dev

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Build and Push Dev Image
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository_owner }}/mybookstore-backend

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Build Docker image with tags
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t $REGISTRY/$IMAGE_NAME:dev -t $REGISTRY/$IMAGE_NAME:sha-$SHORT_SHA ./book-service

      - name: 📤 Push images to GHCR
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker push $REGISTRY/$IMAGE_NAME:dev
          docker push $REGISTRY/$IMAGE_NAME:sha-$SHORT_SHA

      - name: 🌐 Make the image public
        run: |
          curl -X PATCH https://api.github.com/user/packages/container/mybookstore-backend/visibility \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"visibility":"public"}'
